export const TYPES = {
    Bot: Symbol("Bot"),
    Client: Symbol("Client"),
    Token: Symbol("Token"),
    MessageResponder: Symbol("MessageResponder"),
    PavosaurusFinder: Symbol("PavosaurusFinder"),
    BrutishFinder: Symbol("BrutishFinder"),
    ArcaneFinder: Symbol("ArcaneFinder"),
    ScimitopFinder: Symbol("ScimitopFinder"),
    JadinkoFinder: Symbol("JadinkoFinder"),
    VaranusaurFinder: Symbol("VaranusaurFinder"),
    SalamanderFinder: Symbol("SalamanderFinder"),
    FrogFinder: Symbol("FrogFinder"),
    MalletopsFinder: Symbol("MalletopsFinder"),
    OculiFinder: Symbol("OculiFinder"),
    SpicatiFinder: Symbol("SpicatiFinder"),
    AsciatopsFinder: Symbol("AsciatopsFinder"),
    BagradaFinder: Symbol("BagradaFinder"),
    CorbiculaFinder: Symbol("CorbiculaFinder"),
    BreedingFinder: Symbol("BreedingFinder"),
};